ntr_assays = {
    "NTR:0000612": {"assay": ["RNA binding"], "name": "Switchgear"},
    "NTR:0000762": {
        "assay": ["Transcription"],
        "name": "shRNA knockdown followed by RNA-seq",
        "preferred_name": "shRNA RNA-seq",
    },
    "NTR:0000763": {
        "assay": ["Transcription"],
        "name": "siRNA knockdown followed by RNA-seq",
        "preferred_name": "siRNA RNA-seq",
    },
    "NTR:0001132": {
        "assay": ["RNA binding"],
        "name": "RNA Bind-N-Seq",
        "preferred_name": "RNA Bind-N-Seq",
    },
    "NTR:0004774": {
        "assay": ["DNA accessibility"],
        "name": "genetic modification followed by DNase-seq",
        "preferred_name": "GM DNase-seq",
    },
    "NTR:0003814": {
        "assay": ["Transcription"],
        "name": "CRISPR genome editing followed by RNA-seq",
        "preferred_name": "CRISPR RNA-seq",
    },
    "NTR:0004619": {
        "assay": ["Transcription"],
        "name": "CRISPRi followed by RNA-seq",
        "preferred_name": "CRISPRi RNA-seq",
    },
    "NTR:0000433": {
        "assay": ["RNA structure"],
        "name": "in vivo click selective 2-hydroxyl acylation and profiling experiment",
        "preferred_name": "icSHAPE",
    },
    "NTR:0000445": {
        "assay": ["Transcription"],
        "name": "long read RNA sequencing",
        "preferred_name": "long read RNA-seq",
    },
    "NTR:0000458": {
        "assay": ["DNA sequencing"],
        "name": "Clone-seq",
        "preferred_name": "Clone-seq",
    },
    "NTR:0000513": {
        "assay": ["3D chromatin structure"],
        "name": "proximity ligation-assisted ChIP-seq",
        "preferred_name": "PLAC-seq",
    },
    "NTR:0000520": {
        "assay": ["CRISPR screen"],
        "name": "CRISPR screen",
        "preferred_name": "CRISPR screen",
    },
    "NTR:0000538": {
        "assay": ["RNA structure"],
        "name": "in vivo click light activated structural examination of RNA",
        "preferred_name": "icLASER",
    },
    "NTR:0000544": {
        "assay": ["3D chromatin structure"],
        "name": "split-pool recognition of interactions by tag extension",
        "preferred_name": "SPRITE",
    },
    "NTR:0000562": {
        "assay": ["3D chromatin structure"],
        "name": "split-pool recognition of interactions by tag extension with immunoprecipitation",
        "preferred_name": "SPRITE-IP",
    },
    "NTR:0000642": {
        "assay": ["Single cell"],
        "name": "long read single-cell RNA-seq",
        "preferred_name": "long read scRNA-seq",
    },
    "NTR:0000641": {
        "assay": ["Transcription"],
        "name": "GRO-cap",
        "preferred_name": "GRO-cap",
    },
    "NTR:0000640": {
        "assay": ["Transcription"],
        "name": "GRO-seq",
        "preferred_name": "GRO-seq",
    },
    "NTR:0000643": {
        "assay": ["Single cell"],
        "name": "perturbation followed by scRNA-seq",
        "preferred_name": "perturbation followed by scRNA-seq",
    },
    "NTR:0000644": {
        "assay": ["Single cell"],
        "name": "perturbation followed by snATAC-seq",
        "preferred_name": "perturbation followed by snATAC-seq",
    },
    "NTR:0000649": {
        "assay": ["Proteomics"],
        "name": "LC/MS label-free quantitative proteomics",
        "preferred_name": "LC/MS label-free quantitative proteomics",
    },
    "NTR:0000650": {
        "assay": ["Proteomics"],
        "name": "LC-MS/MS isobaric label quantitative proteomics",
        "preferred_name": "LC-MS/MS isobaric label quantitative proteomics",
    },
    "NTR:0000657": {
        "assay": ["CRISPR screen"],
        "name": "proliferation CRISPR screen",
        "preferred_name": "proliferation CRISPR screen",
    },
    "NTR:0000658": {
        "assay": ["CRISPR screen"],
        "name": "FACS CRISPR screen",
        "preferred_name": "FACS CRISPR screen",
    },
    "NTR:0000659": {
        "assay": ["CRISPR screen"],
        "name": "Flow-FISH CRISPR screen",
        "preferred_name": "Flow-FISH CRISPR screen",
    },
    "NTR:0000675": {
        "assay": ["Ribosome activity"],
        "name": "Ribosome activity",
        "preferred_name": "Ribosome activity",
    },
    "NTR:0000676": {
        "assay": ["element activity validation"],
        "name": "genomic perturbation followed by RT-qPCR",
        "preferred_name": "genomic perturbation followed by RT-qPCR",
    },
    "NTR:0000677": {
        "assay": ["element activity validation"],
        "name": "element activity validation",
        "preferred_name": "element activity validation",
    },
}

ntr_biosamples = {
    "NTR:0000491": {
        "developmental": ["mesoderm"],
        "name": "Right ventricle myocardium inferior",
        "organs": ["heart"],
        "systems": ["circulatory system"],
    },
    "NTR:0000492": {
        "developmental": ["mesoderm"],
        "name": "Right ventricle myocardium superior",
        "organs": ["heart"],
        "systems": ["circulatory system"],
    },
    "NTR:0000493": {
        "developmental": ["mesoderm"],
        "name": "left ventricle myocardium inferior",
        "organs": ["heart"],
        "systems": ["circulatory system"],
    },
    "NTR:0000494": {
        "developmental": ["mesoderm"],
        "name": "left ventricle myocardium superior",
        "organs": ["heart"],
        "systems": ["circulatory system"],
    },
    "NTR:0001226": {
        "developmental": ["endoderm"],
        "name": "parathyroid adenoma",
        "organs": ["paraythroid gland"],
        "systems": ["endocrine system"],
    },
    "NTR:0001407": {
        "developmental": ["ectoderm"],
        "name": "germinal matrix",
        "organs": ["brain"],
        "systems": ["central nervous system"],
    },
    "NTR:0002929": {
        "developmental": ["endoderm"],
        "name": "posterior foregut",
        "systems": ["digestive system"],
    },
    "NTR:0003013": {
        "developmental": ["mesoderm"],
        "name": "placental basal plate",
        "organs": ["extraembryonic component", "placenta"],
        "systems": ["reproductive system"],
    },
    "NTR:0005063": {
        "cells": ["stem cell"],
        "name": "dedifferentiated amniotic fluid mesenchymal stem cell",
        "organs": ["connective tissue", "extraembryonic component"],
    },
    "NTR:0004218": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "name": "inflammation-experienced regulatory T-cells",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0004148": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated CD4-positive, CD25-positive, alpha-beta regulatory T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0003079": {
        "cells": ["fibroblast"],
        "name": "fibroblast of breast",
        "organs": ["breast"],
    },
    "NTR:0001801": {
        "cells": ["neural cell", "retinal cell"],
        "developmental": ["ectoderm"],
        "name": "retinal alpha ganglion cell",
        "organs": ["eye"],
        "systems": ["sensory system", "central nervous system"],
    },
    "NTR:0000741": {
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "name": "splenic B cell",
        "organs": ["spleen", "blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000722": {
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "name": "c-Kit-positive CD71-positive TER-119-positive erythroid progenitor cells",
    },
    "NTR:0000721": {
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "name": "c-Kit-positive CD71-positive TER-119-negative erythroid progenitor cells",
    },
    "NTR:0000720": {
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "name": "c-Kit-positive CD71-negative TER-119-negative erythroid progenitor cells",
    },
    "NTR:0000719": {
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "name": "c-Kit-negative CD71-positive TER-119-positive erythroid progenitor cells",
    },
    "NTR:0000714": {"cells": ["stem cell"], "name": "leukemia stem cell"},
    "NTR:0000537": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "name": "activated T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000535": {
        "cells": ["hematopoietic cell", "leukocyte", "NK cell"],
        "name": "CD14-negative natural killer cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000525": {
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of right biceps",
        "organs": ["skin of body"],
        "systems": ["integumental system"],
    },
    "NTR:0000524": {
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of scalp",
        "organs": ["skin of body"],
        "systems": ["integumental system"],
    },
    "NTR:0000523": {
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of right quadriceps",
        "organs": ["skin of body"],
        "systems": ["integumental system"],
    },
    "NTR:0000522": {
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of left quadriceps",
        "organs": ["skin of body"],
        "systems": ["integumental system"],
    },
    "NTR:0000521": {
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of left biceps",
        "organs": ["skin of body"],
        "systems": ["integumental system"],
    },
    "NTR:0000506": {
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "name": "B cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000505": {
        "cells": ["hematopoietic cell", "leukocyte", "dendritic cell", "myeloid cell"],
        "name": "monocyte-derived dendritic cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000504": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "activated CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000503": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "CD8-positive, alpha-beta memory T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000502": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "activated naive CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000501": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "CD8-positive naive resting alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000500": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "activated CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000499": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated CD4-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000498": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "CD4-positive, alpha-beta memory T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000497": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated naive CD4-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000496": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "CD4-positive naive resting alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000495": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated CD4-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000427": {
        "cells": ["stem cell"],
        "developmental": ["ectoderm"],
        "name": "neurosphere",
        "systems": ["central nervous system"],
    },
    "NTR:0005192": {
        "developmental": ["endoderm"],
        "name": "primitive gut cell",
        "organs": ["embryo"],
        "systems": ["digestive system"],
    },
    "NTR:0005188": {
        "developmental": ["endoderm"],
        "name": "definitive endodermal cell",
        "organs": ["embryo"],
    },
    "NTR:0003830": {
        "cells": ["neural cell"],
        "developmental": ["ectoderm"],
        "name": "mid-neurogenesis radial glial cells",
        "systems": ["central nervous system"],
    },
    "NTR:0001484": {
        "developmental": ["endoderm"],
        "name": "islet precursor cell",
        "organs": ["pancreas"],
        "systems": ["endocrine system"],
    },
    "NTR:0000856": {
        "developmental": ["mesoderm", "endoderm"],
        "name": "mesendoderm",
        "organs": ["embryo"],
    },
    "NTR:0000561": {
        "developmental": ["endoderm"],
        "name": "hepatic endoderm",
        "organs": ["exocrine gland", "liver", "endocrine gland"],
        "systems": ["endocrine system", "digestive system"],
    },
    "NTR:0000560": {
        "cells": ["neural cell"],
        "developmental": ["ectoderm"],
        "name": "bipolar spindle neuron",
        "systems": ["central nervous system"],
    },
    "NTR:0000514": {
        "cells": ["progenitor cell"],
        "name": "cardiovascular progenitor cell",
        "systems": ["circulatory system"],
    },
    "NTR:0000512": {
        "cells": ["progenitor cell"],
        "name": "nephron progenitor cell",
        "organs": ["kidney"],
        "systems": ["excretory system"],
    },
    "NTR:0000474": {
        "cells": ["progenitor cell"],
        "developmental": ["ectoderm"],
        "name": "ecto neural progenitor cell",
        "systems": ["central nervous system"],
    },
    "NTR:0000428": {
        "cells": ["stem cell"],
        "name": "embryoid body cell",
        "organs": ["embryo"],
    },
    "NTR:0000646": {
        "developmental": ["ectoderm"],
        "name": "left cerebral cortex",
        "organs": ["brain"],
        "systems": ["central nervous system"],
    },
    "NTR:0000647": {
        "developmental": ["ectoderm"],
        "name": "right cerebral cortex",
        "organs": ["brain"],
        "systems": ["central nervous system"],
    },
    "NTR:0000629": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "activated effector memory CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000661": {
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "developmental": ["mesoderm", "endoderm"],
        "name": "stimulated activated naive B cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000662": {
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "developmental": ["mesoderm", "endoderm"],
        "name": "stimulated activated memory B cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000663": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "developmental": ["mesoderm", "endoderm"],
        "name": "stimulated activated CD4-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000664": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "developmental": ["mesoderm", "endoderm"],
        "name": "stimulated activated naive CD4-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000665": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "developmental": ["mesoderm", "endoderm"],
        "name": "stimulated activated CD4-positive, alpha-beta memory T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000666": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "stimulated activated CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000667": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "stimulated activated naive CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000668": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "stimulated activated effector memory CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000669": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "stimulated activated CD8-positive, alpha-beta memory T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000633": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated T-helper 1 cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000634": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated T-helper 2 cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000635": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated T-helper 17 cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000670": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated T-helper 9 cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000671": {
        "cells": ["hematopoietic cell", "leukocyte", "NK cell"],
        "name": "stimulated natural killer cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000631": {
        "cells": ["hematopoietic cell", "leukocyte", "NK cell"],
        "name": "activated CD16-positive, CD56-dim natural killer cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000632": {
        "cells": ["hematopoietic cell", "leukocyte", "NK cell"],
        "name": "activated CD16-negative, CD56-bright natural killer cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000652": {
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "name": "stimulated activated naive B cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000660": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD4+ T cell"],
        "name": "activated effector memory CD4-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000672": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "name": "activated gamma-delta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000673": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "name": "stimulated activated gamma-delta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000630": {
        "cells": ["hematopoietic cell", "leukocyte", "T cell", "CD8+ T cell"],
        "name": "activated central memory CD8-positive, alpha-beta T cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000636": {
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "developmental": ["mesoderm", "endoderm"],
        "name": "activated memory B cell",
        "organs": ["blood", "bodily fluid"],
        "systems": ["immune system"],
    },
    "NTR:0000754": {
        "cells": ["endothelial cell"],
        "name": "TeloHAEC",
        "organs": ["heart", "aorta"],
        "systems": ["circulatory system"],
    },
}
